/**
 * (c) 2003-2012 MuleSoft, Inc. This software is protected under international
 * copyright law. All use of this software is subject to MuleSoft's Master
 * Subscription Agreement (or other Terms of Service) separately entered
 * into between you and MuleSoft. If such an agreement is not in
 * place, you may not use the software.
 **/

/**
 * This file was automatically generated by the Mule Development Kit
 */

package org.mule.module.documentum;

public class DocumentumConnectorException extends RuntimeException {

    private static final long serialVersionUID = -2109364149460283327L;

    public DocumentumConnectorException(Throwable cause) {
        super(cause);
    }

    public DocumentumConnectorException(String message, Throwable cause) {
        super(message, cause);
    }

    public DocumentumConnectorException(String s) {
        super(s);
    }
}