/**
 * Copyright (c) MuleSoft, Inc. All rights reserved. http://www.mulesoft.com
 *
 * The software in this package is published under the terms of the CPAL v1.0
 * license, a copy of which has been included with this distribution in the
 * LICENSE.md file.
 */
/**
 * This file was automatically generated by the Mule Development Kit
 */

package org.mule.module.documentum;

public class DocumentumConnectorException extends RuntimeException {

    private static final long serialVersionUID = -2109364149460283327L;

    public DocumentumConnectorException(Throwable cause) {
        super(cause);
    }

    public DocumentumConnectorException(String message, Throwable cause) {
        super(message, cause);
    }

    public DocumentumConnectorException(String s) {
        super(s);
    }
}