/**
 *
 * (c) 2003-2012 MuleSoft, Inc. This software is protected under international
 * copyright law. All use of this software is subject to MuleSoft's Master
 * Subscription Agreement (or other Terms of Service) separately entered
 * into between you and MuleSoft. If such an agreement is not in
 * place, you may not use the software.
 */

package com.emc.documentum.fs.rt.services;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.5.1
 * 2013-02-15T15:30:31.410-03:00
 * Generated source version: 2.5.1
 * 
 */
@WebService(targetNamespace = "http://services.rt.fs.documentum.emc.com/", name = "AgentServicePort")
@XmlSeeAlso({com.emc.documentum.fs.datamodel.core.content.ObjectFactory.class, ObjectFactory.class, org.w3._2001.xmlschema.ObjectFactory.class})
public interface AgentServicePort {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getHttpSessionId", targetNamespace = "http://services.rt.fs.documentum.emc.com/", className = "com.emc.documentum.fs.rt.services.GetHttpSessionId")
    @WebMethod
    @ResponseWrapper(localName = "getHttpSessionIdResponse", targetNamespace = "http://services.rt.fs.documentum.emc.com/", className = "com.emc.documentum.fs.rt.services.GetHttpSessionIdResponse")
    public java.lang.String getHttpSessionId();

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getDeploymentId", targetNamespace = "http://services.rt.fs.documentum.emc.com/", className = "com.emc.documentum.fs.rt.services.GetDeploymentId")
    @WebMethod
    @ResponseWrapper(localName = "getDeploymentIdResponse", targetNamespace = "http://services.rt.fs.documentum.emc.com/", className = "com.emc.documentum.fs.rt.services.GetDeploymentIdResponse")
    public java.lang.String getDeploymentId();

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getStatus", targetNamespace = "http://services.rt.fs.documentum.emc.com/", className = "com.emc.documentum.fs.rt.services.GetStatus")
    @WebMethod
    @ResponseWrapper(localName = "getStatusResponse", targetNamespace = "http://services.rt.fs.documentum.emc.com/", className = "com.emc.documentum.fs.rt.services.GetStatusResponse")
    public com.emc.documentum.fs.datamodel.core.content.ProgressInfo getStatus(
        @WebParam(name = "activityInfo", targetNamespace = "")
        com.emc.documentum.fs.datamodel.core.content.ActivityInfo activityInfo
    );
}
