/**
 *
 * (c) 2003-2012 MuleSoft, Inc. This software is protected under international
 * copyright law. All use of this software is subject to MuleSoft's Master
 * Subscription Agreement (or other Terms of Service) separately entered
 * into between you and MuleSoft. If such an agreement is not in
 * place, you may not use the software.
 */

package com.emc.documentum.fs.services.core.acl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.5.1
 * 2013-02-26T11:38:11.939-03:00
 * Generated source version: 2.5.1
 * 
 */
@WebServiceClient(name = "AccessControlService", 
                  wsdlLocation = "classpath:wsdl/AccessControlService.wsdl",
                  targetNamespace = "http://acl.core.services.fs.documentum.emc.com/") 
public class AccessControlService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://acl.core.services.fs.documentum.emc.com/", "AccessControlService");
    public final static QName AccessControlServicePort = new QName("http://acl.core.services.fs.documentum.emc.com/", "AccessControlServicePort");
    static {
        URL url = AccessControlService.class.getClassLoader().getResource("wsdl/AccessControlService.wsdl");
        if (url == null) {
            java.util.logging.Logger.getLogger(AccessControlService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "classpath:wsdl/AccessControlService.wsdl");
        }       
        WSDL_LOCATION = url;
    }

    public AccessControlService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public AccessControlService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AccessControlService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns AccessControlServicePort
     */
    @WebEndpoint(name = "AccessControlServicePort")
    public AccessControlServicePort getAccessControlServicePort() {
        return super.getPort(AccessControlServicePort, AccessControlServicePort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AccessControlServicePort
     */
    @WebEndpoint(name = "AccessControlServicePort")
    public AccessControlServicePort getAccessControlServicePort(WebServiceFeature... features) {
        return super.getPort(AccessControlServicePort, AccessControlServicePort.class, features);
    }

}
