/**
 *
 * (c) 2003-2012 MuleSoft, Inc. This software is protected under international
 * copyright law. All use of this software is subject to MuleSoft's Master
 * Subscription Agreement (or other Terms of Service) separately entered
 * into between you and MuleSoft. If such an agreement is not in
 * place, you may not use the software.
 */

package com.emc.documentum.fs.services.core.acl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.5.1
 * 2013-02-26T11:38:11.867-03:00
 * Generated source version: 2.5.1
 * 
 */
@WebService(targetNamespace = "http://acl.core.services.fs.documentum.emc.com/", name = "AccessControlServicePort")
@XmlSeeAlso({com.emc.documentum.fs.datamodel.core.ObjectFactory.class, com.emc.documentum.fs.datamodel.core.acl.ObjectFactory.class, com.emc.documentum.fs.rt.ObjectFactory.class, ObjectFactory.class})
public interface AccessControlServicePort {

    @RequestWrapper(localName = "delete", targetNamespace = "http://acl.core.services.fs.documentum.emc.com/", className = "com.emc.documentum.fs.services.core.acl.Delete")
    @WebMethod
    @ResponseWrapper(localName = "deleteResponse", targetNamespace = "http://acl.core.services.fs.documentum.emc.com/", className = "com.emc.documentum.fs.services.core.acl.DeleteResponse")
    public void delete(
        @WebParam(name = "aclIdentities", targetNamespace = "")
        java.util.List<com.emc.documentum.fs.datamodel.core.acl.AclIdentity> aclIdentities
    ) throws ServiceException, CoreServiceException_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "update", targetNamespace = "http://acl.core.services.fs.documentum.emc.com/", className = "com.emc.documentum.fs.services.core.acl.Update")
    @WebMethod
    @ResponseWrapper(localName = "updateResponse", targetNamespace = "http://acl.core.services.fs.documentum.emc.com/", className = "com.emc.documentum.fs.services.core.acl.UpdateResponse")
    public com.emc.documentum.fs.datamodel.core.acl.AclPackage update(
        @WebParam(name = "aclPackage", targetNamespace = "")
        com.emc.documentum.fs.datamodel.core.acl.AclPackage aclPackage
    ) throws ServiceException, CoreServiceException_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "create", targetNamespace = "http://acl.core.services.fs.documentum.emc.com/", className = "com.emc.documentum.fs.services.core.acl.Create")
    @WebMethod
    @ResponseWrapper(localName = "createResponse", targetNamespace = "http://acl.core.services.fs.documentum.emc.com/", className = "com.emc.documentum.fs.services.core.acl.CreateResponse")
    public com.emc.documentum.fs.datamodel.core.acl.AclPackage create(
        @WebParam(name = "aclPackage", targetNamespace = "")
        com.emc.documentum.fs.datamodel.core.acl.AclPackage aclPackage
    ) throws ServiceException, CoreServiceException_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "get", targetNamespace = "http://acl.core.services.fs.documentum.emc.com/", className = "com.emc.documentum.fs.services.core.acl.Get")
    @WebMethod
    @ResponseWrapper(localName = "getResponse", targetNamespace = "http://acl.core.services.fs.documentum.emc.com/", className = "com.emc.documentum.fs.services.core.acl.GetResponse")
    public com.emc.documentum.fs.datamodel.core.acl.AclPackage get(
        @WebParam(name = "aclIdentities", targetNamespace = "")
        java.util.List<com.emc.documentum.fs.datamodel.core.acl.AclIdentity> aclIdentities
    ) throws ServiceException, CoreServiceException_Exception;
}
