/**
 *
 * (c) 2003-2012 MuleSoft, Inc. This software is protected under international
 * copyright law. All use of this software is subject to MuleSoft's Master
 * Subscription Agreement (or other Terms of Service) separately entered
 * into between you and MuleSoft. If such an agreement is not in
 * place, you may not use the software.
 */


package com.emc.documentum.fs.services.core.acl;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.5.1
 * 2013-02-26T11:38:11.859-03:00
 * Generated source version: 2.5.1
 */

@WebFault(name = "CoreServiceException", targetNamespace = "http://acl.core.services.fs.documentum.emc.com/")
public class CoreServiceException_Exception extends Exception {
    
    private com.emc.documentum.fs.services.core.acl.CoreServiceException coreServiceException;

    public CoreServiceException_Exception() {
        super();
    }
    
    public CoreServiceException_Exception(String message) {
        super(message);
    }
    
    public CoreServiceException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public CoreServiceException_Exception(String message, com.emc.documentum.fs.services.core.acl.CoreServiceException coreServiceException) {
        super(message);
        this.coreServiceException = coreServiceException;
    }

    public CoreServiceException_Exception(String message, com.emc.documentum.fs.services.core.acl.CoreServiceException coreServiceException, Throwable cause) {
        super(message, cause);
        this.coreServiceException = coreServiceException;
    }

    public com.emc.documentum.fs.services.core.acl.CoreServiceException getFaultInfo() {
        return this.coreServiceException;
    }
}
