/**
 *
 * (c) 2003-2012 MuleSoft, Inc. This software is protected under international
 * copyright law. All use of this software is subject to MuleSoft's Master
 * Subscription Agreement (or other Terms of Service) separately entered
 * into between you and MuleSoft. If such an agreement is not in
 * place, you may not use the software.
 */


package com.emc.documentum.fs.services.core.acl;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.5.1
 * 2013-02-26T11:38:11.715-03:00
 * Generated source version: 2.5.1
 */

@WebFault(name = "ServiceException", targetNamespace = "http://rt.fs.documentum.emc.com/")
public class ServiceException extends Exception {
    
    private com.emc.documentum.fs.rt.ServiceException serviceException;

    public ServiceException() {
        super();
    }
    
    public ServiceException(String message) {
        super(message);
    }
    
    public ServiceException(String message, Throwable cause) {
        super(message, cause);
    }

    public ServiceException(String message, com.emc.documentum.fs.rt.ServiceException serviceException) {
        super(message);
        this.serviceException = serviceException;
    }

    public ServiceException(String message, com.emc.documentum.fs.rt.ServiceException serviceException, Throwable cause) {
        super(message, cause);
        this.serviceException = serviceException;
    }

    public com.emc.documentum.fs.rt.ServiceException getFaultInfo() {
        return this.serviceException;
    }
}
