/**
 * Copyright (c) MuleSoft, Inc. All rights reserved. http://www.mulesoft.com
 *
 * The software in this package is published under the terms of the CPAL v1.0
 * license, a copy of which has been included with this distribution in the
 * LICENSE.md file.
 */
/**
 * This file was automatically generated by the Mule Development Kit
 */

package org.mule.modules.documentum.automation.system;

import org.junit.Before;
import org.junit.Test;
import org.mule.api.ConnectionException;
import org.mule.api.MuleException;
import org.mule.modules.documentum.Config;
import org.mule.modules.documentum.DocumentumConnector;

import com.emc.documentum.fs.services.core.SerializableException;
import com.emc.documentum.fs.services.core.acl.CoreServiceException_Exception;
import com.emc.documentum.fs.services.core.acl.ServiceException;

public class DocumentumConnectorTestDriver {

    private static final String USER = "user";
    private static final String PASSWORD = "password";
    private static final String REPOSITORY = "repository";
    private static final String SERVER = "http://localhost:9080/";
    private static Config config;

    @Before
    public void init() throws ConnectionException, MuleException {
        config = new Config();
        config.connect(USER, PASSWORD, REPOSITORY, SERVER);
    }

    @Test
    public void testGetAcls() throws ServiceException, CoreServiceException_Exception, SerializableException {
        DocumentumConnector connector = new DocumentumConnector();

        connector.setConfig(config);
        connector.getAcls();
    }

}