/**
 * Copyright (c) MuleSoft, Inc. All rights reserved. http://www.mulesoft.com
 *
 * The software in this package is published under the terms of the CPAL v1.0
 * license, a copy of which has been included with this distribution in the
 * LICENSE.md file.
 */
/**
 * This file was automatically generated by the Mule Development Kit
 */

package org.mule.modules.documentum.automation.system;

import org.junit.Before;
import org.junit.Test;

public class DocumentumConnectorTest {

    @Before
    public void initContext() {
        // TODO
    }

    @Test
    public void myTest() throws Exception {
        // TODO
    }

}