/**
 *
 * (c) 2003-2012 MuleSoft, Inc. This software is protected under international
 * copyright law. All use of this software is subject to MuleSoft's Master
 * Subscription Agreement (or other Terms of Service) separately entered
 * into between you and MuleSoft. If such an agreement is not in
 * place, you may not use the software.
 */

/**
 * This file was automatically generated by the Mule Development Kit
 */

package org.mule.module.documentum.coreServices;

import java.util.ArrayList;
import java.util.List;

import javax.xml.ws.BindingProvider;
import javax.xml.ws.handler.Handler;
import javax.xml.ws.handler.HandlerResolver;
import javax.xml.ws.handler.PortInfo;

import com.emc.documentum.fs.datamodel.core.acl.Acl;
import com.emc.documentum.fs.datamodel.core.acl.AclEntry;
import com.emc.documentum.fs.datamodel.core.acl.AclIdentity;
import com.emc.documentum.fs.datamodel.core.acl.AclPackage;
import com.emc.documentum.fs.datamodel.core.acl.AclType;
import com.emc.documentum.fs.datamodel.core.acl.AclVisibility;
import com.emc.documentum.fs.datamodel.core.context.RepositoryIdentity;
import com.emc.documentum.fs.datamodel.core.context.ServiceContext;
import com.emc.documentum.fs.services.core.acl.AccessControlService;
import com.emc.documentum.fs.services.core.acl.AccessControlServicePort;
import com.emc.documentum.fs.services.core.acl.CoreServiceException_Exception;
import com.emc.documentum.fs.services.core.acl.ServiceException;

public class AccessControlUtil extends Util {
    
    private String userName;
    private String repositoryName;
    private AccessControlServicePort port;
    
    public AccessControlUtil(ServiceContext serviceContext, String target) {
        setAccessControlPort(serviceContext, target);
        this.repositoryName = ((RepositoryIdentity) (serviceContext.getIdentities().get(0))).getRepositoryName();
        this.userName = ((RepositoryIdentity) (serviceContext.getIdentities().get(0))).getUserName();
    }
    
    public Acl createAcl(String aclName, String aclDescription, List<AclEntry> aclEntries, AclVisibility aclVisibility, AclType aclType) throws ServiceException, CoreServiceException_Exception {        
        return port.create(createAclPackage(createAcl(createAclIdentity(repositoryName, userName, aclName), aclDescription, aclType, aclVisibility, aclEntries))).getAcls().get(0);
    }
    
    public AclPackage getAcl(List<String> aclNames) throws ServiceException, CoreServiceException_Exception {
        List<AclIdentity> aclIdentityList = new ArrayList<AclIdentity>();
        for (String aclName: aclNames) {
            aclIdentityList.add(createAclIdentity(repositoryName, userName, aclName));
        }
        return port.get(aclIdentityList);
    }
    
    public Acl updateAcl(String aclName, String aclDescription, List<AclEntry> aclEntries, AclVisibility aclVisibility, AclType aclType) throws ServiceException, CoreServiceException_Exception {        
        return port.update(createAclPackage(createAcl(createAclIdentity(repositoryName, userName, aclName), aclDescription, aclType, aclVisibility, aclEntries))).getAcls().get(0);
    }
    
    public List<String> deleteAcl(List<String> aclNames) throws ServiceException, CoreServiceException_Exception {
        List<AclIdentity> aclIdentityList = new ArrayList<AclIdentity>();
        for (String aclName: aclNames) {
            aclIdentityList.add(createAclIdentity(repositoryName, userName, aclName));
        }
        port.delete(aclIdentityList);
        return aclNames;
    }
    
    private AclIdentity createAclIdentity(String repositoryName, String userName, String aclName) {
        AclIdentity aclIdentity = new AclIdentity();
        aclIdentity.setRepositoryName(repositoryName);
        aclIdentity.setDomain(userName);
        aclIdentity.setName(aclName);
        return aclIdentity;
    }
    
    private Acl createAcl(AclIdentity aclIdentity, String aclDescription, AclType aclType, AclVisibility aclVisibility, List<AclEntry> aclEntries) {
        Acl acl = new Acl();
        acl.setIdentity(aclIdentity);
        acl.setDescription(aclDescription);
        acl.setSystemCreated(false);
        acl.setType(aclType);
        acl.setVisibility(aclVisibility);
        acl.getEntries().addAll(aclEntries);
        return acl;
    }
    
    private AclPackage createAclPackage(Acl acl) {
        AclPackage aclPackage = new AclPackage();
        List<Acl> aclList = new ArrayList<Acl>();
        aclList.add(acl);
        aclPackage.getAcls().addAll(aclList);
        return aclPackage;
    }
    
    private void setAccessControlPort(final ServiceContext context, String target) {
        AccessControlService accessControlService = new AccessControlService();
        accessControlService.setHandlerResolver(new HandlerResolver() {
            @SuppressWarnings("rawtypes")
            public List<Handler> getHandlerChain(PortInfo info) {
                List<Handler> handlerList = new ArrayList<Handler>();
                handlerList.add(new HeaderHandler(context));
                return handlerList;
            }
        });
        port = accessControlService.getAccessControlServicePort();
        ((BindingProvider) port).getRequestContext().put(BindingProvider.ENDPOINT_ADDRESS_PROPERTY, target + "core/AccessControlService");
    }
    
}