/**
 *
 * (c) 2003-2012 MuleSoft, Inc. This software is protected under international
 * copyright law. All use of this software is subject to MuleSoft's Master
 * Subscription Agreement (or other Terms of Service) separately entered
 * into between you and MuleSoft. If such an agreement is not in
 * place, you may not use the software.
 */

/**
 * This file was automatically generated by the Mule Development Kit
 */

package org.mule.module.documentum.coreServices;

import java.util.ArrayList;
import java.util.List;

import javax.xml.ws.BindingProvider;
import javax.xml.ws.handler.Handler;
import javax.xml.ws.handler.HandlerResolver;
import javax.xml.ws.handler.PortInfo;

import com.emc.documentum.fs.datamodel.core.CacheStrategyType;
import com.emc.documentum.fs.datamodel.core.context.RepositoryIdentity;
import com.emc.documentum.fs.datamodel.core.context.ServiceContext;
import com.emc.documentum.fs.datamodel.core.query.PassthroughQuery;
import com.emc.documentum.fs.datamodel.core.query.QueryExecution;
import com.emc.documentum.fs.datamodel.core.query.QueryResult;
import com.emc.documentum.fs.services.core.QueryService;
import com.emc.documentum.fs.services.core.QueryServicePort;
import com.emc.documentum.fs.services.core.SerializableException;

public class QueryUtil extends Util {
    
    private String repositoryName;
    private QueryServicePort port;
    
    public QueryUtil(ServiceContext serviceContext, String target) {
        setQueryPort(serviceContext, target);
        this.repositoryName = ((RepositoryIdentity) (serviceContext.getIdentities().get(0))).getRepositoryName();
    }
    
    public QueryResult query(String dqlStatement, QueryExecution queryExecution) throws SerializableException {
        PassthroughQuery query = createQuery(dqlStatement);
        if (queryExecution == null) {
            return port.execute(query, createQueryExecution(CacheStrategyType.NO_CACHE_STRATEGY), null);
        }
        else {
            QueryResult queryResult = port.execute(query, queryExecution, null);
            queryExecution.setStartingIndex(queryExecution.getStartingIndex() + queryExecution.getMaxResultCount());
            return queryResult;   
        }
    }
    
    private PassthroughQuery createQuery(String dqlStatement) {
        PassthroughQuery query = new PassthroughQuery();
        query.setQueryString(dqlStatement);
        query.getRepositories().add(repositoryName);
        return query;
    }
    
    private QueryExecution createQueryExecution(CacheStrategyType cacheStrategyType) {
        QueryExecution queryEx = new QueryExecution();
        queryEx.setCacheStrategyType(cacheStrategyType);
        return queryEx;
    }
    
    private void setQueryPort(final ServiceContext context, String target) {
        QueryService queryService = new QueryService();
        queryService.setHandlerResolver(new HandlerResolver() {
            @SuppressWarnings("rawtypes")
            public List<Handler> getHandlerChain(PortInfo info) {
                List<Handler> handlerList = new ArrayList<Handler>();
                handlerList.add(new HeaderHandler(context));
                return handlerList;
            }
        });        
        port = queryService.getQueryServicePort();
        ((BindingProvider) port).getRequestContext().put(BindingProvider.ENDPOINT_ADDRESS_PROPERTY, target + "core/QueryService");
    }

}