/**
 *
 * (c) 2003-2012 MuleSoft, Inc. This software is protected under international
 * copyright law. All use of this software is subject to MuleSoft's Master
 * Subscription Agreement (or other Terms of Service) separately entered
 * into between you and MuleSoft. If such an agreement is not in
 * place, you may not use the software.
 */

/**
 * This file was automatically generated by the Mule Development Kit
 */

package org.mule.module.documentum.coreServices;

import java.io.IOException;
import java.util.List;

import com.emc.documentum.fs.datamodel.core.CheckoutInfo;
import com.emc.documentum.fs.datamodel.core.ObjectIdentity;
import com.emc.documentum.fs.datamodel.core.VersionInfo;
import com.emc.documentum.fs.datamodel.core.VersionStrategy;
import com.emc.documentum.fs.datamodel.core.content.ContentTransferMode;
import com.emc.documentum.fs.services.core.SerializableException;

public interface VersionControlClient {

    public CheckoutInfo getCheckoutInfo(ObjectIdentity objIdentity) throws SerializableException;
    
    public ObjectIdentity checkout(ObjectIdentity objIdentity) throws SerializableException;
    
    public ObjectIdentity checkin(ObjectIdentity objIdentity, String newContentPath, VersionStrategy versionStrategy, List<String> labels, boolean isRetainLock, ContentTransferMode transferMode) throws SerializableException, IOException;
    
    public ObjectIdentity cancelCheckout(ObjectIdentity objIdentity) throws SerializableException;
    
    public ObjectIdentity deleteVersion(ObjectIdentity objIdentity) throws SerializableException;
    
    public ObjectIdentity deleteAllVersions(ObjectIdentity objIdentity) throws SerializableException;
    
    public ObjectIdentity getCurrent(ObjectIdentity objIdentity) throws SerializableException;
    
    public VersionInfo getVersionInfo(ObjectIdentity objIdentity) throws SerializableException;
    
}