/**
 * Copyright (c) MuleSoft, Inc. All rights reserved. http://www.mulesoft.com
 *
 * The software in this package is published under the terms of the CPAL v1.0
 * license, a copy of which has been included with this distribution in the
 * LICENSE.md file.
 */
/**
 * This file was automatically generated by the Mule Development Kit
 */

package org.mule.module.documentum.coreservices;

import java.io.IOException;
import java.util.List;

import com.emc.documentum.fs.datamodel.core.CheckoutInfo;
import com.emc.documentum.fs.datamodel.core.ObjectIdentity;
import com.emc.documentum.fs.datamodel.core.VersionInfo;
import com.emc.documentum.fs.datamodel.core.VersionStrategy;
import com.emc.documentum.fs.datamodel.core.content.ContentTransferMode;
import com.emc.documentum.fs.services.core.SerializableException;

public interface VersionControlClient {

    public CheckoutInfo getCheckoutInfo(ObjectIdentity objIdentity) throws SerializableException;

    public ObjectIdentity checkout(ObjectIdentity objIdentity) throws SerializableException;

    public ObjectIdentity checkin(ObjectIdentity objIdentity, String newContentPath, VersionStrategy versionStrategy, List<String> labels, boolean isRetainLock,
            ContentTransferMode transferMode) throws SerializableException, IOException;

    public ObjectIdentity cancelCheckout(ObjectIdentity objIdentity) throws SerializableException;

    public ObjectIdentity deleteVersion(ObjectIdentity objIdentity) throws SerializableException;

    public ObjectIdentity deleteAllVersions(ObjectIdentity objIdentity) throws SerializableException;

    public ObjectIdentity getCurrent(ObjectIdentity objIdentity) throws SerializableException;

    public VersionInfo getVersionInfo(ObjectIdentity objIdentity) throws SerializableException;

}