/**
 *
 * (c) 2003-2012 MuleSoft, Inc. This software is protected under international
 * copyright law. All use of this software is subject to MuleSoft's Master
 * Subscription Agreement (or other Terms of Service) separately entered
 * into between you and MuleSoft. If such an agreement is not in
 * place, you may not use the software.
 */

package com.emc.documentum.fs.services.core;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.5.1
 * 2013-02-15T15:30:33.454-03:00
 * Generated source version: 2.5.1
 * 
 */
@WebService(targetNamespace = "http://core.services.fs.documentum.emc.com/", name = "VersionControlServicePort")
@XmlSeeAlso({com.emc.documentum.fs.datamodel.core.profiles.ObjectFactory.class, com.emc.documentum.fs.datamodel.core.ObjectFactory.class, com.emc.documentum.fs.datamodel.core.content.ObjectFactory.class, com.emc.documentum.fs.datamodel.core.properties.ObjectFactory.class, com.emc.documentum.fs.rt.ObjectFactory.class, com.emc.documentum.fs.datamodel.core.query.ObjectFactory.class, org.w3._2001.xmlschema.ObjectFactory.class, ObjectFactory.class})
public interface VersionControlServicePort {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getVersionInfo", targetNamespace = "http://core.services.fs.documentum.emc.com/", className = "com.emc.documentum.fs.services.core.GetVersionInfo")
    @WebMethod
    @ResponseWrapper(localName = "getVersionInfoResponse", targetNamespace = "http://core.services.fs.documentum.emc.com/", className = "com.emc.documentum.fs.services.core.GetVersionInfoResponse")
    public java.util.List<com.emc.documentum.fs.datamodel.core.VersionInfo> getVersionInfo(
        @WebParam(name = "objectIdentitySet", targetNamespace = "")
        com.emc.documentum.fs.datamodel.core.ObjectIdentitySet objectIdentitySet
    ) throws SerializableException;

    @RequestWrapper(localName = "cancelCheckout", targetNamespace = "http://core.services.fs.documentum.emc.com/", className = "com.emc.documentum.fs.services.core.CancelCheckout")
    @WebMethod
    @ResponseWrapper(localName = "cancelCheckoutResponse", targetNamespace = "http://core.services.fs.documentum.emc.com/", className = "com.emc.documentum.fs.services.core.CancelCheckoutResponse")
    public void cancelCheckout(
        @WebParam(name = "objectIdentitySet", targetNamespace = "")
        com.emc.documentum.fs.datamodel.core.ObjectIdentitySet objectIdentitySet
    ) throws SerializableException;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getCurrent", targetNamespace = "http://core.services.fs.documentum.emc.com/", className = "com.emc.documentum.fs.services.core.GetCurrent")
    @WebMethod
    @ResponseWrapper(localName = "getCurrentResponse", targetNamespace = "http://core.services.fs.documentum.emc.com/", className = "com.emc.documentum.fs.services.core.GetCurrentResponse")
    public com.emc.documentum.fs.datamodel.core.DataPackage getCurrent(
        @WebParam(name = "forObjects", targetNamespace = "")
        com.emc.documentum.fs.datamodel.core.ObjectIdentitySet forObjects,
        @WebParam(name = "options", targetNamespace = "")
        com.emc.documentum.fs.datamodel.core.OperationOptions options
    ) throws SerializableException;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "checkout", targetNamespace = "http://core.services.fs.documentum.emc.com/", className = "com.emc.documentum.fs.services.core.Checkout")
    @WebMethod
    @ResponseWrapper(localName = "checkoutResponse", targetNamespace = "http://core.services.fs.documentum.emc.com/", className = "com.emc.documentum.fs.services.core.CheckoutResponse")
    public com.emc.documentum.fs.datamodel.core.DataPackage checkout(
        @WebParam(name = "objectIdentitySet", targetNamespace = "")
        com.emc.documentum.fs.datamodel.core.ObjectIdentitySet objectIdentitySet,
        @WebParam(name = "options", targetNamespace = "")
        com.emc.documentum.fs.datamodel.core.OperationOptions options
    ) throws SerializableException;

    @RequestWrapper(localName = "deleteVersion", targetNamespace = "http://core.services.fs.documentum.emc.com/", className = "com.emc.documentum.fs.services.core.DeleteVersion")
    @WebMethod
    @ResponseWrapper(localName = "deleteVersionResponse", targetNamespace = "http://core.services.fs.documentum.emc.com/", className = "com.emc.documentum.fs.services.core.DeleteVersionResponse")
    public void deleteVersion(
        @WebParam(name = "objectsToDelete", targetNamespace = "")
        com.emc.documentum.fs.datamodel.core.ObjectIdentitySet objectsToDelete
    ) throws SerializableException;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getCheckoutInfo", targetNamespace = "http://core.services.fs.documentum.emc.com/", className = "com.emc.documentum.fs.services.core.GetCheckoutInfo")
    @WebMethod
    @ResponseWrapper(localName = "getCheckoutInfoResponse", targetNamespace = "http://core.services.fs.documentum.emc.com/", className = "com.emc.documentum.fs.services.core.GetCheckoutInfoResponse")
    public java.util.List<com.emc.documentum.fs.datamodel.core.CheckoutInfo> getCheckoutInfo(
        @WebParam(name = "objectIdentitySet", targetNamespace = "")
        com.emc.documentum.fs.datamodel.core.ObjectIdentitySet objectIdentitySet
    ) throws SerializableException;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "checkin", targetNamespace = "http://core.services.fs.documentum.emc.com/", className = "com.emc.documentum.fs.services.core.Checkin")
    @WebMethod
    @ResponseWrapper(localName = "checkinResponse", targetNamespace = "http://core.services.fs.documentum.emc.com/", className = "com.emc.documentum.fs.services.core.CheckinResponse")
    public com.emc.documentum.fs.datamodel.core.DataPackage checkin(
        @WebParam(name = "dataPackage", targetNamespace = "")
        com.emc.documentum.fs.datamodel.core.DataPackage dataPackage,
        @WebParam(name = "versionStrategy", targetNamespace = "")
        com.emc.documentum.fs.datamodel.core.VersionStrategy versionStrategy,
        @WebParam(name = "isRetainLock", targetNamespace = "")
        boolean isRetainLock,
        @WebParam(name = "symbolicLabels", targetNamespace = "")
        java.util.List<java.lang.String> symbolicLabels,
        @WebParam(name = "options", targetNamespace = "")
        com.emc.documentum.fs.datamodel.core.OperationOptions options
    ) throws SerializableException;

    @RequestWrapper(localName = "deleteAllVersions", targetNamespace = "http://core.services.fs.documentum.emc.com/", className = "com.emc.documentum.fs.services.core.DeleteAllVersions")
    @WebMethod
    @ResponseWrapper(localName = "deleteAllVersionsResponse", targetNamespace = "http://core.services.fs.documentum.emc.com/", className = "com.emc.documentum.fs.services.core.DeleteAllVersionsResponse")
    public void deleteAllVersions(
        @WebParam(name = "objectIdentitySet", targetNamespace = "")
        com.emc.documentum.fs.datamodel.core.ObjectIdentitySet objectIdentitySet
    ) throws SerializableException;
}
